services:
  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik:/etc/traefik:ro
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.entrypoints=web-secure
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.services.api@internal.loadbalancer.server.port=8080
  keycloak:
    image: jboss/keycloak:16.1.1
    volumes:
      - ./config/keycloak.json:/mnt/keycloak.json:ro
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /mnt/keycloak.json
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_FRONTEND_URL: https://keycloak.localhost/auth
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.tls=true
      - traefik.http.routers.keycloak.entrypoints=web-secure
      - traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
  # We spin up a separate test DB to keep it pristine and undisturbed from dev runs;
  # crucially, the seeds should NEVER run on these test DB's!!
  postgres-test:
    image: postgres:14-alpine
    ports:
      - 54320:5432
    environment:
      POSTGRES_DB: blink
      POSTGRES_USER: knex
      POSTGRES_HOST_AUTH_METHOD: trust
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - public
  redis-test:
    image: redis:7-alpine
    ports:
      - 63790:6379
    networks:
      - public

networks:
  public:
    external: true
